// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ESII2025d2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250403202856_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ESII2025d2.Models.CategoriaTalento", b =>
                {
                    b.Property<int>("cod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("cod"));

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("cod");

                    b.ToTable("CategoriaTalento");
                });

            modelBuilder.Entity("ESII2025d2.Models.Cliente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("empresa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("idutilizador")
                        .HasColumnType("integer");

                    b.Property<string>("numerotelefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("idutilizador");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("ESII2025d2.Models.Experiencia", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("anocomeco")
                        .HasColumnType("integer");

                    b.Property<int?>("anofim")
                        .HasColumnType("integer");

                    b.Property<int>("idtalento")
                        .HasColumnType("integer");

                    b.Property<string>("nomeempresa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("idtalento");

                    b.ToTable("Experiencia");
                });

            modelBuilder.Entity("ESII2025d2.Models.PropostaTrabalho", b =>
                {
                    b.Property<int>("cod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("cod"));

                    b.Property<int?>("cattalento_cod")
                        .HasColumnType("integer");

                    b.Property<int?>("cliente_id")
                        .HasColumnType("integer");

                    b.Property<int>("codskill")
                        .HasColumnType("integer");

                    b.Property<string>("descricao")
                        .HasColumnType("text");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("numtotalhoras")
                        .HasColumnType("integer");

                    b.HasKey("cod");

                    b.HasIndex("cattalento_cod");

                    b.HasIndex("cliente_id");

                    b.HasIndex("codskill");

                    b.ToTable("PropostaTrabalho");
                });

            modelBuilder.Entity("ESII2025d2.Models.Skill", b =>
                {
                    b.Property<int>("cod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("cod"));

                    b.Property<string>("area")
                        .HasColumnType("text");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("cod");

                    b.ToTable("Skill");
                });

            modelBuilder.Entity("ESII2025d2.Models.Talento", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("codcategoriatalento")
                        .HasColumnType("integer");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("idutilizador")
                        .HasColumnType("integer");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pais")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("precohora")
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.HasIndex("codcategoriatalento");

                    b.HasIndex("idutilizador");

                    b.ToTable("Talento");
                });

            modelBuilder.Entity("ESII2025d2.Models.TalentoSkill", b =>
                {
                    b.Property<int>("codskill")
                        .HasColumnType("integer");

                    b.Property<int>("anosexperiencia")
                        .HasColumnType("integer");

                    b.Property<int>("idtalento")
                        .HasColumnType("integer");

                    b.HasKey("codskill");

                    b.HasIndex("idtalento");

                    b.ToTable("TalentoSkill");
                });

            modelBuilder.Entity("ESII2025d2.Models.Utilizador", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateOnly>("datanascimento")
                        .HasColumnType("date");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("palavra_passe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Utilizador");
                });

            modelBuilder.Entity("ESII2025d2.Models.Cliente", b =>
                {
                    b.HasOne("ESII2025d2.Models.Utilizador", "idutilizadorNavigation")
                        .WithMany("Clientes")
                        .HasForeignKey("idutilizador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("idutilizadorNavigation");
                });

            modelBuilder.Entity("ESII2025d2.Models.Experiencia", b =>
                {
                    b.HasOne("ESII2025d2.Models.Talento", "idtalentoNavigation")
                        .WithMany("Experiencia")
                        .HasForeignKey("idtalento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("idtalentoNavigation");
                });

            modelBuilder.Entity("ESII2025d2.Models.PropostaTrabalho", b =>
                {
                    b.HasOne("ESII2025d2.Models.CategoriaTalento", "cattalento_codNavigation")
                        .WithMany("PropostaTrabalhos")
                        .HasForeignKey("cattalento_cod");

                    b.HasOne("ESII2025d2.Models.Cliente", "cliente")
                        .WithMany("PropostaTrabalhos")
                        .HasForeignKey("cliente_id");

                    b.HasOne("ESII2025d2.Models.Skill", "codskillNavigation")
                        .WithMany("PropostaTrabalhos")
                        .HasForeignKey("codskill")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cattalento_codNavigation");

                    b.Navigation("cliente");

                    b.Navigation("codskillNavigation");
                });

            modelBuilder.Entity("ESII2025d2.Models.Talento", b =>
                {
                    b.HasOne("ESII2025d2.Models.CategoriaTalento", "codcategoriatalentoNavigation")
                        .WithMany("Talentos")
                        .HasForeignKey("codcategoriatalento");

                    b.HasOne("ESII2025d2.Models.Utilizador", "idutilizadorNavigation")
                        .WithMany("Talentos")
                        .HasForeignKey("idutilizador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("codcategoriatalentoNavigation");

                    b.Navigation("idutilizadorNavigation");
                });

            modelBuilder.Entity("ESII2025d2.Models.TalentoSkill", b =>
                {
                    b.HasOne("ESII2025d2.Models.Skill", "codskillNavigation")
                        .WithMany("TalentoSkills")
                        .HasForeignKey("codskill")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ESII2025d2.Models.Talento", "idtalentoNavigation")
                        .WithMany("TalentoSkills")
                        .HasForeignKey("idtalento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("codskillNavigation");

                    b.Navigation("idtalentoNavigation");
                });

            modelBuilder.Entity("ESII2025d2.Models.CategoriaTalento", b =>
                {
                    b.Navigation("PropostaTrabalhos");

                    b.Navigation("Talentos");
                });

            modelBuilder.Entity("ESII2025d2.Models.Cliente", b =>
                {
                    b.Navigation("PropostaTrabalhos");
                });

            modelBuilder.Entity("ESII2025d2.Models.Skill", b =>
                {
                    b.Navigation("PropostaTrabalhos");

                    b.Navigation("TalentoSkills");
                });

            modelBuilder.Entity("ESII2025d2.Models.Talento", b =>
                {
                    b.Navigation("Experiencia");

                    b.Navigation("TalentoSkills");
                });

            modelBuilder.Entity("ESII2025d2.Models.Utilizador", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Talentos");
                });
#pragma warning restore 612, 618
        }
    }
}
